#' Create a Gazepoint HTML diagnostic report
#'
#' Creates a lightweight HTML report from a `gp3tools` workflow result object.
#' The report includes dataset dimensions, sampling-rate checks, flagged
#' recordings, AOI summaries, and standard diagnostic plots.
#'
#' @param results A named list returned by `run_gazepoint_workflow()`.
#' @param output_file Path to the HTML report file to create.
#' @param title Report title.
#' @param overwrite Logical. If `FALSE`, stop when the report file already exists.
#' @param max_rows Maximum number of rows to show in preview tables.
#' @param save_plots Logical. If `TRUE`, save and include diagnostic plots.
#' @param plot_dir Optional folder where report plot files should be saved.
#' If `NULL`, a folder next to the report is created.
#'
#' @return A tibble with the written report path and plot folder.
#' @export
create_gazepoint_report <- function(
    results,
    output_file,
    title = "Gazepoint diagnostic report",
    overwrite = TRUE,
    max_rows = 30,
    save_plots = TRUE,
    plot_dir = NULL
) {
  if (!is.list(results)) {
    rlang::abort("`results` must be a list returned by `run_gazepoint_workflow()`.")
  }

  required_results <- c(
    "sampling",
    "quality",
    "flagged_quality",
    "aoi_table"
  )

  missing_results <- setdiff(required_results, names(results))

  if (length(missing_results) > 0) {
    rlang::abort(
      paste0(
        "`results` is missing required elements: ",
        paste(missing_results, collapse = ", ")
      )
    )
  }

  if (file.exists(output_file) && !overwrite) {
    rlang::abort(paste0("Report file already exists: ", output_file))
  }

  output_dir <- dirname(output_file)

  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }

  if (is.null(plot_dir)) {
    report_name <- tools::file_path_sans_ext(basename(output_file))
    plot_dir <- file.path(output_dir, paste0(report_name, "_files"))
  }

  written_plots <- NULL

  if (isTRUE(save_plots)) {
    written_plots <- save_gazepoint_plots(
      flagged_quality = results$flagged_quality,
      sampling = results$sampling,
      output_dir = plot_dir,
      prefix = "report",
      overwrite = overwrite
    )
  }

  n_all_gaze <- if ("all_gaze" %in% names(results)) {
    nrow(results$all_gaze)
  } else {
    NA_integer_
  }

  n_all_fix <- if ("all_fix" %in% names(results)) {
    nrow(results$all_fix)
  } else {
    NA_integer_
  }

  n_sampling_rows <- nrow(results$sampling)
  n_quality_rows <- nrow(results$quality)
  n_aoi_rows <- nrow(results$aoi_table)

  n_flagged <- if ("review_required" %in% names(results$flagged_quality)) {
    sum(results$flagged_quality$review_required %in% TRUE, na.rm = TRUE)
  } else {
    NA_integer_
  }

  flagged_rows <- results$flagged_quality

  if ("review_required" %in% names(flagged_rows)) {
    flagged_rows <- flagged_rows[
      flagged_rows$review_required %in% TRUE,
      ,
      drop = FALSE
    ]
  }

  overview <- data.frame(
    item = c(
      "All-gaze rows",
      "Fixation rows",
      "Sampling summary rows",
      "Tracking-quality rows",
      "AOI summary rows",
      "Rows requiring review"
    ),
    value = c(
      n_all_gaze,
      n_all_fix,
      n_sampling_rows,
      n_quality_rows,
      n_aoi_rows,
      n_flagged
    )
  )

  plot_html <- ""

  if (!is.null(written_plots) && nrow(written_plots) > 0) {
    plot_paths <- file.path(
      basename(plot_dir),
      basename(written_plots$file)
    )

    plot_blocks <- paste0(
      "<h3>",
      .gp3_html_escape(written_plots$plot),
      "</h3>\n",
      "<img src='",
      .gp3_html_escape(plot_paths),
      "' alt='",
      .gp3_html_escape(written_plots$plot),
      "' />\n",
      collapse = "\n"
    )

    plot_html <- paste0(
      "<h2>Diagnostic plots</h2>\n",
      plot_blocks
    )
  }

  html <- paste0(
    "<!DOCTYPE html>\n",
    "<html>\n",
    "<head>\n",
    "<meta charset='utf-8'>\n",
    "<title>", .gp3_html_escape(title), "</title>\n",
    "<style>\n",
    "body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.4; }\n",
    "h1, h2, h3 { color: #222; }\n",
    "table { border-collapse: collapse; margin-bottom: 24px; width: 100%; font-size: 13px; }\n",
    "th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }\n",
    "th { background: #f2f2f2; }\n",
    "img { max-width: 100%; height: auto; border: 1px solid #ddd; margin-bottom: 24px; }\n",
    ".note { background: #f8f8f8; padding: 12px; border-left: 4px solid #999; }\n",
    "</style>\n",
    "</head>\n",
    "<body>\n",
    "<h1>", .gp3_html_escape(title), "</h1>\n",
    "<p class='note'>Generated by <strong>gp3tools</strong>.</p>\n",

    "<h2>Overview</h2>\n",
    .gp3_html_table(overview, max_rows = max_rows),

    "<h2>Recordings requiring review</h2>\n",
    if (nrow(flagged_rows) == 0) {
      "<p>No recordings were flagged for review.</p>\n"
    } else {
      .gp3_html_table(flagged_rows, max_rows = max_rows)
    },

    "<h2>Sampling-rate summary</h2>\n",
    .gp3_html_table(results$sampling, max_rows = max_rows),

    "<h2>Tracking-quality summary</h2>\n",
    .gp3_html_table(results$quality, max_rows = max_rows),

    "<h2>AOI summary</h2>\n",
    .gp3_html_table(results$aoi_table, max_rows = max_rows),

    plot_html,

    "<h2>Interpretation note</h2>\n",
    "<p>This report is intended as a diagnostic screening report. ",
    "Rows flagged for review should be inspected before statistical analysis. ",
    "Metrics recomputed from exported all-gaze and fixation rows may not exactly ",
    "match Gazepoint Analysis internal summary calculations.</p>\n",

    "</body>\n",
    "</html>\n"
  )

  writeLines(html, output_file, useBytes = TRUE)

  tibble::tibble(
    report = output_file,
    plot_dir = plot_dir,
    n_flagged = n_flagged
  )
}

.gp3_html_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x <- gsub("'", "&#39;", x, fixed = TRUE)
  x
}

.gp3_html_table <- function(data, max_rows = 30) {
  if (!is.data.frame(data)) {
    return("<p>No table available.</p>\n")
  }

  if (nrow(data) == 0) {
    return("<p>No rows available.</p>\n")
  }

  n_total <- nrow(data)

  data <- utils::head(data, max_rows)
  data <- as.data.frame(data)

  header <- paste0(
    "<tr>",
    paste0(
      "<th>",
      .gp3_html_escape(names(data)),
      "</th>",
      collapse = ""
    ),
    "</tr>\n"
  )

  rows <- apply(data, 1, function(row) {
    row[is.na(row)] <- ""
    paste0(
      "<tr>",
      paste0(
        "<td>",
        .gp3_html_escape(row),
        "</td>",
        collapse = ""
      ),
      "</tr>"
    )
  })

  note <- if (n_total > max_rows) {
    paste0(
      "<p><em>Showing first ",
      max_rows,
      " of ",
      n_total,
      " rows.</em></p>\n"
    )
  } else {
    ""
  }

  paste0(
    note,
    "<table>\n",
    "<thead>\n",
    header,
    "</thead>\n",
    "<tbody>\n",
    paste(rows, collapse = "\n"),
    "\n</tbody>\n",
    "</table>\n"
  )
}
