# Generated by install-validation-integration-v2.R.
# British canonical aliases for established American exports.

#' British-spelling alias for `summarize_gazepoint_coordinate_coverage()`
#'
#' @param ... Arguments passed to [summarize_gazepoint_coordinate_coverage()].
#' @return The result of [summarize_gazepoint_coordinate_coverage()].
#' @export
summarise_gazepoint_coordinate_coverage <- function(...) {
  summarize_gazepoint_coordinate_coverage(...)
}

#' British-spelling alias for `summarize_gazepoint_face_reactivity()`
#'
#' @param ... Arguments passed to [summarize_gazepoint_face_reactivity()].
#' @return The result of [summarize_gazepoint_face_reactivity()].
#' @export
summarise_gazepoint_face_reactivity <- function(...) {
  summarize_gazepoint_face_reactivity(...)
}

#' British-spelling alias for `summarize_gazepoint_face_windows()`
#'
#' @param ... Arguments passed to [summarize_gazepoint_face_windows()].
#' @return The result of [summarize_gazepoint_face_windows()].
#' @export
summarise_gazepoint_face_windows <- function(...) {
  summarize_gazepoint_face_windows(...)
}

#' British-spelling alias for `summarize_gazepoint_pupil_response_features()`
#'
#' @param ... Arguments passed to [summarize_gazepoint_pupil_response_features()].
#' @return The result of [summarize_gazepoint_pupil_response_features()].
#' @export
summarise_gazepoint_pupil_response_features <- function(...) {
  summarize_gazepoint_pupil_response_features(...)
}

#' British-spelling alias for `summarize_gazepoint_time_clusters()`
#'
#' @param ... Arguments passed to [summarize_gazepoint_time_clusters()].
#' @return The result of [summarize_gazepoint_time_clusters()].
#' @export
summarise_gazepoint_time_clusters <- function(...) {
  summarize_gazepoint_time_clusters(...)
}

